#!/bin/bash
set -eu

packages_dir=${1:-/packages}
debs=()
appimages=()
declare -A appimage_commands=()

shopt -s nullglob
debs=("$packages_dir"/*.deb)
appimages=("$packages_dir"/*.AppImage "$packages_dir"/*.appimage "$packages_dir"/*.APPIMAGE)
shopt -u nullglob

install_debs() {
    if [ ${#debs[@]} -eq 0 ]; then
        echo "[i] No local .deb packages found in $packages_dir; skipping."
        return 0
    fi

    echo "[i] Installing local .deb packages from $packages_dir"
    apt-get update
    apt-get install -y --no-install-recommends "${debs[@]}"
    apt-get clean
    rm -rf /var/lib/apt/lists/*
    echo "[ok] Local .deb packages installed."
}

appimage_command_name() {
    local stem=$1

    stem=${stem%.*}
    printf '%s' "$stem" |
        tr '[:upper:]' '[:lower:]' |
        sed -E \
            -e 's/([._-])v?[0-9]+([._-][0-9]+)*([._+-].*)?$//' \
            -e 's/[^a-z0-9]+/-/g' \
            -e 's/-+/-/g' \
            -e 's/^-//; s/-$//'
}

install_appimages() {
    local source filename normalized command destination app_dir launcher
    local staged_image extract_dir extracted_app

    cleanup_staging() {
        rm -rf "$extract_dir"
        rm -f "$staged_image"
    }

    if [ ${#appimages[@]} -eq 0 ]; then
        echo "[i] No local AppImage files found in $packages_dir; skipping."
        return 0
    fi

    # Resolve every command first so a collision cannot leave a partial install.
    for source in "${appimages[@]}"; do
        filename=$(basename "$source")
        normalized=$(appimage_command_name "$filename")
        if [ -z "$normalized" ]; then
            echo "[e] AppImage filename cannot be converted to a command: $filename" >&2
            exit 1
        fi
        command=$normalized
        launcher="/usr/local/bin/$command"

        if [ -n "${appimage_commands[$command]+x}" ]; then
            echo "[e] AppImage command collision: $filename and ${appimage_commands[$command]} both map to $command" >&2
            exit 1
        fi
        if { [ -e "$launcher" ] || [ -L "$launcher" ]; } &&
            ! grep -q '^# Generated by vibe-install-local-apps$' "$launcher" 2>/dev/null; then
            echo "[e] AppImage command conflicts with an existing executable: $command" >&2
            exit 1
        fi
        appimage_commands[$command]=$filename
    done

    install -d -m 0755 /opt/appimages
    for source in "${appimages[@]}"; do
        filename=$(basename "$source")
        command=$(appimage_command_name "$filename")
        destination="/opt/appimages/$command.AppImage"
        app_dir="/opt/appimages/$command.AppDir"
        launcher="/usr/local/bin/$command"
        staged_image="/opt/appimages/.$command.AppImage.new.$$"
        extract_dir=$(mktemp -d /opt/appimages/.extract.XXXXXX)

        install -m 0755 "$source" "$staged_image"
        if ! (cd "$extract_dir" && "$staged_image" --appimage-extract >/dev/null); then
            cleanup_staging
            echo "[e] AppImage extraction failed (unsupported runtime or architecture): $filename" >&2
            exit 1
        fi

        extracted_app="$extract_dir/squashfs-root"
        if [ ! -x "$extracted_app/AppRun" ]; then
            cleanup_staging
            echo "[e] AppImage does not contain an executable AppRun: $filename" >&2
            exit 1
        fi

        rm -rf "$app_dir"
        mv "$extracted_app" "$app_dir"
        chmod -R a+rX "$app_dir"
        chmod 0755 "$app_dir/AppRun"
        rm -rf "$extract_dir"
        mv -f "$staged_image" "$destination"
        chmod 0755 "$destination"
        printf '#!/bin/bash\n# Generated by vibe-install-local-apps\nexec vibe-run-appimage %q %q "$@"\n' \
            "$app_dir" "$destination" >"$launcher"
        chmod 0755 "$launcher"
        echo "[ok] AppImage installed: $filename -> $command"
    done
}

install_debs
install_appimages
