#!/bin/bash
set -eu

VIBE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib.sh
source "$VIBE_DIR/lib.sh"

build_image() {
    log_step "building image: $IMAGE_NAME"
    local toolchain_refresh
    toolchain_refresh=$(date +%Y%m%d%H%M%S)
    "$RUNTIME" build \
        --build-arg "USERID=$USERID" \
        --build-arg "USERNAME=$USERNAME" \
        --build-arg "WORKSPACE=$WORKSPACE" \
        --build-arg "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" \
        --build-arg "TOOLCHAIN_REFRESH=$toolchain_refresh" \
        -f "$VIBE_SHARED_DIR/Containerfile" -t "$IMAGE_NAME" "$VIBE_SHARED_DIR"
    log_ok "image built: $IMAGE_NAME"
}

remove_existing_container() {
    remove_container_everywhere "${CONTAINER_NAME:-vibespace}" "container"
}

create_container() {
    log_step "creating container: $CONTAINER_NAME"
    "$RUNTIME" run -d \
        --net host \
        --name "$CONTAINER_NAME" \
        -w "$WORKSPACE" \
        --shm-size=1g \
        "${RUNTIME_RUN_OPTS[@]}" \
        --ulimit core=0 \
        --cpus="$CPU_LIMIT" --cpuset-cpus="0-$((CPU_LIMIT - 1))" \
        --memory="$MEMORY_RAM" --memory-swap="$MEMORY_SWAP" \
        -v "$WORKSPACE:$WORKSPACE${VOL_PRIVATE}" \
        -v "$VOL_OPT:/opt" \
        -v "$VOL_HOME:/home/$USERNAME${VOL_PRIVATE}" \
        -e "DOCKER_HOST=$DOCKER_PROXY_HOST" \
        -e ELECTRON_DISABLE_SANDBOX=1 \
        -e ELECTRON_OZONE_PLATFORM_HINT=wayland \
        -e MOZ_ENABLE_WAYLAND=wayland \
        -e GDK_BACKEND=wayland \
        -e QT_QPA_PLATFORM=wayland \
        -e SDL_VIDEODRIVER=wayland \
        -e WAYLAND_DISPLAY="$WAYLAND_DISPLAY" \
        -e XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
        --volume "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY${VOL_PRIVATE}" \
        --volume /dev/dri:/dev/dri \
        --device /dev/dri \
        "$IMAGE_NAME"
    log_ok "container running: $CONTAINER_NAME"
}

config_fish_render() {
    local template=$1

    sed \
        -e "s/^set -gx VIBE_RUNTIME podman/set -gx VIBE_RUNTIME $RUNTIME/" \
        -e "s/vibespace/$CONTAINER_NAME/g" \
        -e "s|/w|$WORKSPACE|g" \
        "$template"
}

install_host_fish_config() {
    local fish_dir fish_file
    fish_dir="$HOME/.config/fish/conf.d"
    fish_file="$fish_dir/vibespace.fish"

    log_step "installing host fish config: $fish_file"
    mkdir -p "$fish_dir"

    {
        echo "# Generated by linux/vibe.sh - re-run ./linux/vibe.sh to update"
        config_fish_render "$VIBE_DIR/config.fish"
    } >"$fish_file"

    log_ok "host fish config installed: $fish_file"
}

print_helpers() {
    cat <<EOF
${green}Vibespace is ready.${reset}
${cyan}Enter:${reset} vibe
${cyan}Attach:${reset} $RUNTIME exec -it $CONTAINER_NAME fish
${cyan}Host fish:${reset} ~/.config/fish/conf.d/vibespace.fish
${cyan}Docker proxy:${reset} $VIBE_DIR/docker-proxy.sh

${cyan}Suggested container fish config (~/.config/fish/conf.d/vibespace.fish inside vibespace):${reset}
${dim}---${reset}
set fish_greeting

eval "\$(~/.local/bin/mise activate fish)"

export ELECTRON_OZONE_PLATFORM_HINT=wayland
export XDG_SESSION_TYPE=wayland

alias antigravity="/bin/antigravity --ozone-platform=wayland"
${dim}---${reset}
EOF
}

require_wayland
parse_vibe_args "$@"
resolve_runtime
resolve_runtime_run_opts
docker_proxy_main

echo "${green}Setting up vibespace with options:"
resolve_vibe_paths
print_vibe_paths
echo

prepare_vibe_volumes

build_image
remove_existing_container
create_container
install_host_fish_config
print_helpers
print_docker_security_notices
